### ISSUE TITLE
ais_decode_normed build

### ISSUE THREAD

**Issue by AsbjornPettersen** [schwehr/libais#108]
Tried to manually build libais.lib and ais_decode_normed.cpp from MS VisualStudio 2013.
Patched in main():
1 . //build_nmea_lookup();

2.
  Ais5 m5(fields[5].c_str()); 
to
  libais:Ais5 m5(fields[5].c_str(),2);

Haven't tested it much, but this should be placed in "utils/ais_decode_normed/" since it can be used for dumping NMEA of files.

**Comment by schwehr** [comment]
Thanks for those notes.  I plan on pushing more of my C++ code to this project and to rewrite the TAG_BLOCK and USCG metadata python handlers as C++.
