### ISSUE TITLE
Try using (drop nose) py.test for the test suite

### ISSUE THREAD

**Issue by schwehr** [schwehr/libais#113]
setup.py:

    setup_requires=['nose>=1.0'],
    test_suite='nose.collector',

setup.cfg:

    [nosetests]
    exe=True

**Comment by schwehr** [comment]
SkyTruth switched away from nose:

py.test, because it gives better failure messages and has fixtures, which nose can't emulate, so we can't support both.

To run a single test file: 

    py.test tests/test_base.py

To run a single test function: 

    py.test tests/test_base.py::test_wrong_mode

**Comment by geowurster** [comment]
@schwehr [`pytest-cov`](https://pypi.python.org/pypi/pytest-cov) for coverage reports:

```console
$ py.test test --cov ais --cov-report term-missing
```

And to support `python setup.py test`, create a [`cmdclass`](https://github.com/SkyTruth/gpsdio/blob/master/setup.py#L18-L34) and give it to [`setup()`](https://github.com/SkyTruth/gpsdio/blob/master/setup.py#L62).  I don't think I technically have the argument related stuff set properly in `PyTest()`, but it works.
