### ISSUE TITLE
File-like object for interacting with the parser

### ISSUE THREAD

**Issue by geowurster** [schwehr/libais#114]
A pattern that is becoming more and more prominent in Python libraries, and even the stdlib, is something like:

```python
import ais

with ais.open('file.nmea') as src:
    for msg in src:
        print(msg)
```

Where each `msg` is a parsed dictionary and `src` is a file-like object.  Down the road the file-like object could also maintain a `stats` property and other state information that keeps track of things like number of messages that failed to parse, message types seen, min and max timestamps, etc.

**Comment by schwehr** [comment]
It would be great for open to take a str/unicode thing to open or a file like object

**Comment by geowurster** [comment]
And `-` for stdin to support downstream CLI applications.
