### ISSUE TITLE
Memory leaks in AIS message 20

### ISSUE THREAD

**Issue by gpcimino** [schwehr/libais#116]
Hello everybody,

i am using libais from Python 2.7.10 32 bit ([MSC v.1500 32 bit (Intel)]) on Windows 7 64 bit.
Parsing huge AIS files increases the Python memory footprint up to process crash.
I separated AIS message 20 sentences and the other types in two distinct files. Only when i parse the files with message id 20 memory is  leaking. If you want to give it a try, the file is here:

https://www.dropbox.com/s/zdela2220v5lww9/AISMessage20_only.zip?dl=0

and the code i used is as follow:

    with open("AISMessage20_only.nmea") as f:
        for msg in ais.stream.decode(f):
            print msg

Does anybody have the same issue?
Thanks
GP

**Comment by lmillefiori** [comment]
This doesn't seem related to compiler and platform. 
I'm having the same issue on Linux (Ubuntu 14.04.3 LTS).

A run with `valgrind` shows that there might be a memory leak in `ais_py.cpp` after all.
The complete log is available at https://goo.gl/Zw9YoE, but this is the important part: 

    236,504 bytes in 799 blocks are possibly lost in loss record 1,441 of 1,444
       at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
       by 0x51E674: _PyObject_GC_Malloc (gcmodule.c:1499)
       by 0x51E727: _PyObject_GC_New (gcmodule.c:1521)
       by 0x456BD4: PyDict_New (dictobject.c:277)
       by 0x657D556: libais::ais20_to_pydict(char const*, unsigned long) (ais_py.cpp:2377)
       by 0x658156A: decode (ais_py.cpp:2721)
       by 0x562F72: PyCFunction_Call (methodobject.c:81)
       by 0x4D49D3: call_function (ceval.c:4035)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
       by 0x4D4E9C: fast_function (ceval.c:4121)
       by 0x4D4BA7: call_function (ceval.c:4056)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
    
    238,576 bytes in 806 blocks are possibly lost in loss record 1,442 of 1,444
       at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
       by 0x51E674: _PyObject_GC_Malloc (gcmodule.c:1499)
       by 0x51E727: _PyObject_GC_New (gcmodule.c:1521)
       by 0x456BD4: PyDict_New (dictobject.c:277)
       by 0x657D729: libais::ais20_to_pydict(char const*, unsigned long) (ais_py.cpp:2386)
       by 0x658156A: decode (ais_py.cpp:2721)
       by 0x562F72: PyCFunction_Call (methodobject.c:81)
       by 0x4D49D3: call_function (ceval.c:4035)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
       by 0x4D4E9C: fast_function (ceval.c:4121)
       by 0x4D4BA7: call_function (ceval.c:4056)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
    
    238,872 bytes in 807 blocks are possibly lost in loss record 1,443 of 1,444
       at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
       by 0x51E674: _PyObject_GC_Malloc (gcmodule.c:1499)
       by 0x51E727: _PyObject_GC_New (gcmodule.c:1521)
       by 0x456BD4: PyDict_New (dictobject.c:277)
       by 0x657D8FC: libais::ais20_to_pydict(char const*, unsigned long) (ais_py.cpp:2395)
       by 0x658156A: decode (ais_py.cpp:2721)
       by 0x562F72: PyCFunction_Call (methodobject.c:81)
       by 0x4D49D3: call_function (ceval.c:4035)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
       by 0x4D4E9C: fast_function (ceval.c:4121)
       by 0x4D4BA7: call_function (ceval.c:4056)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
    
    238,872 bytes in 807 blocks are possibly lost in loss record 1,444 of 1,444
       at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
       by 0x51E674: _PyObject_GC_Malloc (gcmodule.c:1499)
       by 0x51E727: _PyObject_GC_New (gcmodule.c:1521)
       by 0x456BD4: PyDict_New (dictobject.c:277)
       by 0x657DACF: libais::ais20_to_pydict(char const*, unsigned long) (ais_py.cpp:2404)
       by 0x658156A: decode (ais_py.cpp:2721)
       by 0x562F72: PyCFunction_Call (methodobject.c:81)
       by 0x4D49D3: call_function (ceval.c:4035)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
       by 0x4D4E9C: fast_function (ceval.c:4121)
       by 0x4D4BA7: call_function (ceval.c:4056)
       by 0x4CF900: PyEval_EvalFrameEx (ceval.c:2681)
    
    LEAK SUMMARY:
       definitely lost: 0 bytes in 0 blocks
       indirectly lost: 0 bytes in 0 blocks
         possibly lost: 3,008,684 bytes in 41,026 blocks
       still reachable: 1,447,529 bytes in 20,658 blocks
            suppressed: 0 bytes in 0 blocks


The related code, potentially responsible for this leak is:

```c++
  PyObject *list = PyList_New(list_size);

  {
    PyObject *reservation = PyDict_New();
    DictSafeSetItem(reservation, "offset", msg.offset_1);
    DictSafeSetItem(reservation, "num_slots", msg.num_slots_1);
    DictSafeSetItem(reservation, "timeout", msg.timeout_1);
    DictSafeSetItem(reservation, "incr", msg.incr_1);
    PyList_SetItem(list, 0, reservation);
  }

  if (msg.group_valid_2) {
    PyObject *reservation = PyDict_New();
    DictSafeSetItem(reservation, "offset", msg.offset_2);
    DictSafeSetItem(reservation, "num_slots", msg.num_slots_2);
    DictSafeSetItem(reservation, "timeout", msg.timeout_2);
    DictSafeSetItem(reservation, "incr", msg.incr_2);
    PyList_SetItem(list, 1, reservation);
  }

  if (msg.group_valid_3) {
    PyObject *reservation = PyDict_New();
    DictSafeSetItem(reservation, "offset", msg.offset_3);
    DictSafeSetItem(reservation, "num_slots", msg.num_slots_3);
    DictSafeSetItem(reservation, "timeout", msg.timeout_3);
    DictSafeSetItem(reservation, "incr", msg.incr_3);
    PyList_SetItem(list, 2, reservation);
  }

  if (msg.group_valid_4) {
    PyObject *reservation = PyDict_New();
    DictSafeSetItem(reservation, "offset", msg.offset_4);
    DictSafeSetItem(reservation, "num_slots", msg.num_slots_4);
    DictSafeSetItem(reservation, "timeout", msg.timeout_4);
    DictSafeSetItem(reservation, "incr", msg.incr_4);
    PyList_SetItem(list, 3, reservation);
  }
```
