### ISSUE TITLE
Release prep cleanup

### ISSUE THREAD

**Issue by geowurster** [schwehr/libais#125]
In preparation for `v0.16`

- [x] Close PR #119
- [x] Close PR #117
- [x] Convert readme to RST
- [x] Convert changelog to Markdown
- [x] Move `VERSION` -> `ais/__init__.py`
- [x] Move `ais_lut.py` -> `ais/enums|lut.py` (or something similar?  looks like they're not in use)
- [x] Move `maritime_id_codes.py` -> `utils`
- [x] Put `Apache 2.0` in `ais.__license__`
- [x] Remove `libais_decode` from `console_scripts` in `setup.py` - doesn't exist
- [x] Delete `nagios_pg_ais.py`
- [x] Delete `nais2pg.py`
- [x] Delete `create.sql`
- [x] Delete `TODO.org` (unlessn needed)
- [x] Add deprecation warning to `bin/aisdecode`
- [x] Add deprecation warning to `ais.stream` and `ais.compatibility`
- [x] Update readme with `ais.open()` example (After #117 is closed)
- [x] Update `MANIFEST.in`
- [x] Update `setup.py`

**Comment by geowurster** [comment]
@schwehr The `libais_decode` script points to `ais.decode.main()` except the `decode` module doesn't exist anymore.  Should I remove that util as well?

**Comment by schwehr** [comment]
I think that got added without the decode module getting added.  Definitely remove it.
