### ISSUE TITLE
Remove redundant value casting

### ISSUE THREAD

**Issue by geowurster** [schwehr/libais#126]
For https://github.com/schwehr/libais/issues/123 we let the `Parse()` functions be responsible for casting values to their Python types.  Turns out that this is _also_ being handled by the various `Queue()` classes within `libais`.  This only needs to happen in one place and the `Parse()` functions are as close to the data as we can get so I propose we leave the casting there and remove the redundant calls in the `Queue()` classes.

For example, in [`ais.vdm.Parse()`](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L106-L125) we cast the appropriate values to numeric types.  This function is then used to [parse](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L153) a message but [every](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L168) [numeric](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L171) [field](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L187) [is](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L188) cast again to the appropriate type when it is [added to the queue](https://github.com/schwehr/libais/blob/master/ais/vdm.py#L143-L233).

**Comment by schwehr** [comment]
These should be basically a noop.  Not a high priority unless someday we see these calls showing up in profile metrics at some point.  e.g.

https://github.com/ymichael/cprofilev
