### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by geowurster** [schwehr/libais#132]
Right now messages are logged to the `root` logger, which makes it difficult to extract `libais` specific errors:

`ERROR:root:Unable to decode: Ais24: AIS_ERR_BAD_MSG_CONTENT`

```python
import logging

logger = logging.getLogger('libais')

logger.error('Unable to decode: Ais24: AIS_ERR_BAD_MSG_CONTENT')
```

Would give us:

`ERROR:libais:Unable to decode: Ais24: AIS_ERR_BAD_MSG_CONTENT`

**Comment by schwehr** [comment]
Yes, logging really needs to go to a specific channel
