### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: bitset set argument out of range

### ISSUE THREAD

**Issue by mkatgert** [schwehr/libais#137]
Libais 0.16 on OS X, Python 3.5.1, installed via pip.

AIVDM-message: !AIVDM,1,1,,B,65E4;r5I0Q9R04D0@01000000000,0*69

On running:
`ais.decode('65E4;r5I0Q9R04D0@01000000000', 0)`
Python crashes with the following error:
`libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: bitset set argument out of range`

It is probably a malformed message but it's difficult to intercept in a DecodeError exception if Python crashes...

**Comment by anitagraser** [comment]
Same issue here. Here are some of the payloads that crash libais:

    "8<CSH0l0@00",
    "64W6V<0r`R720400",
    "65TcPt=HQaT004D0@00000000000",
    "6815DM278u=004D0@0@000000000"

**Comment by mikechiang2003** [comment]
Is any update on this issues? we are facing the same problem.
for this message
!AIVDM,1,1,,A,677Dg2<s=9o004D0@16P00000000,0*72
>>> ais.decode('677Dg2<s=9o004D0@16P00000000',0)
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: bitset set argument out of range
Abort trap: 6

**Comment by schwehr** [comment]
@mikechiang2003 I was able to decode the message from head 
 at https://github.com/schwehr/libais/commit/f2419b4f1ec699dafad4a903f15ca735c7f9198b on Ubuntu 14.04.

```
virtualenv ve
source ve/bin/activate
python setup.py develop
ipython
import ais
ais.decode('677Dg2<s=9o004D0@16P00000000', 0)
Out[2]: 
{u'ack_dac': 1L,
 u'ack_fi': 1L,
 u'ai_available': 1L,
 u'ai_response': 1L,
 u'dac': 1L,
 u'fi': 5L,
 u'id': 6L,
 u'mmsi': 477441800L,
 u'mmsi_dest': 248326000L,
 u'repeat_indicator': 0L,
 u'retransmit': True,
 u'seq': 3L,
 u'seq_num': 1L,
 u'spare': 1L}
```

I will make a test case for this and run it through ASAN and MSAN

**Comment by schwehr** [comment]
oops... the correct tests coming in a bit
