### ISSUE TITLE
Valid AIS Message is parsed incorrectly.

### ISSUE THREAD

**Issue by mb12** [schwehr/libais#141]
Here is an Ais Message 1 that should be parsed correctly. But its not.

!AIVDM,1,1,,A,13n@oD0PB@0IRqvQj@W;EppH088t19uvPT,0*3E

Verified that the message is valid and parseable with other parsers. I've included below a link to an online parser that can be used to verify as well.

http://www.maritec.co.za/tools/aisvdmvdodecoding/

This is why the error occurs.

```
  if (pad != 0 || num_chars != 28) { <== num_chars is 34 for this message.
    status = AIS_ERR_BAD_BIT_COUNT;
    return;
  }
```

**Comment by schwehr** [comment]
AIS message 1 is supposed to only be 168 bits.

```
>>> m = '13n@oD0PB@0IRqvQj@W;EppH088t19uvPT'
>>> len(m)
34
>>> len(m) * 6
204
```
<img width="605" alt="ais1-2-3" src="https://user-images.githubusercontent.com/389869/33156489-10cf78d0-cfaf-11e7-9c70-4575d6ebdaa0.png">
