### ISSUE TITLE
Ais6_1_5 message is always parsed incorrectly. 

### ISSUE THREAD

**Issue by alex-700** [schwehr/libais#157]
Here is something wrong. Second parameter (len) should be at most 32.
spare = bs.ToUnsignedInt(119, 49);
I suggest comment spare at all :)

**Comment by himikof** [comment]
For reference: this message is defined in ITU-R M.1371-5 Annex 5 (International function message 5, table 33). The "spare" field at the end is reserved and should not be read at all.

**Comment by schwehr** [comment]
Fixed by https://github.com/schwehr/libais/pull/148 / 65cb1b12d65ebab97a34f4e54daaae81eab4b949 and https://github.com/schwehr/libais/pull/163
