### ISSUE TITLE
installation error cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

### ISSUE THREAD

**Issue by Retep1972** [schwehr/libais#176]
Going slightly mad. Trying to install libais on a raspberry pi but keep getting a warning an the installation is stopped. See the terminal output below:

running build
running build_py
running build_ext
building '_ais' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/libais/ais_py.cpp -o build/temp.linux-armv7l-2.7/src/libais/ais_py.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++

I can't figure out what is going wrong.

**Comment by jamtho** [comment]
Are you absolutely sure it's that warning that stops the build? There isn't any more console output following it?

**Comment by Retep1972** [comment]
I double checked it an this is indeed the only output. I don't get a prompt also. It just keeps producing the same line over and over until I do a ctrl-c

**Comment by Retep1972** [comment]
To soon.. After some time it comes with this:
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-armv7l-2.7/src/libais/ais_py.o build/temp.linux-armv7l-2.7/src/libais/ais.o build/temp.linux-armv7l-2.7/src/libais/ais_bitset.o build/temp.linux-armv7l-2.7/src/libais/ais1_2_3.o build/temp.linux-armv7l-2.7/src/libais/ais4_11.o build/temp.linux-armv7l-2.7/src/libais/ais5.o build/temp.linux-armv7l-2.7/src/libais/ais6.o build/temp.linux-armv7l-2.7/src/libais/ais7_13.o build/temp.linux-armv7l-2.7/src/libais/ais8.o build/temp.linux-armv7l-2.7/src/libais/ais8_1_22.o build/temp.linux-armv7l-2.7/src/libais/ais8_1_26.o build/temp.linux-armv7l-2.7/src/libais/ais8_200.o build/temp.linux-armv7l-2.7/src/libais/ais8_366.o build/temp.linux-armv7l-2.7/src/libais/ais8_367.o build/temp.linux-armv7l-2.7/src/libais/ais9.o build/temp.linux-armv7l-2.7/src/libais/ais10.o build/temp.linux-armv7l-2.7/src/libais/ais12.o build/temp.linux-armv7l-2.7/src/libais/ais14.o build/temp.linux-armv7l-2.7/src/libais/ais15.o build/temp.linux-armv7l-2.7/src/libais/ais16.o build/temp.linux-armv7l-2.7/src/libais/ais17.o build/temp.linux-armv7l-2.7/src/libais/ais18.o build/temp.linux-armv7l-2.7/src/libais/ais19.o build/temp.linux-armv7l-2.7/src/libais/ais20.o build/temp.linux-armv7l-2.7/src/libais/ais21.o build/temp.linux-armv7l-2.7/src/libais/ais22.o build/temp.linux-armv7l-2.7/src/libais/ais23.o build/temp.linux-armv7l-2.7/src/libais/ais24.o build/temp.linux-armv7l-2.7/src/libais/ais25.o build/temp.linux-armv7l-2.7/src/libais/ais26.o build/temp.linux-armv7l-2.7/src/libais/ais27.o -o build/lib.linux-armv7l-2.7/_ais.so
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/aisdecode -> build/scripts-2.7
changing mode of build/scripts-2.7/aisdecode from 644 to 755

After that sudo python2 setup.py install seems to run without errors.. I will do some testing and come back if it still does not work. Thanks for your help so far!
