### ISSUE TITLE
Different parsing in libais and gpsd

### ISSUE THREAD

**Issue by redhog** [schwehr/libais#67]
gpsdecode produces an invalid latitude value for the following NMEA, while libais does not. So which value is correct? The NMEA was found in the wild... I'm submitting this here in addition to in the gpsd bug tracker as there is no guarantee that the libais value is correct either (maybe the message itself is malformed?):

!AIVDM,1,1,1,A,A;wUJKU>io;WlWuwH`W1PpnuN<isf;5iHtOM1S6q?vsvNrNGOqLcr5mfD6t,2*51,d-127,S1378,t024436.00,T36.76385108,r09SCHA1,1272422678

aisdecode
{"repeat": 0, "spare2": 18, "mmsi": "804870766", "lon": 134.44833374023438, "scaled": true, "lat": -44.6966667175293, "spare": 1, "device": "stdin", "type": 17, "class": "AIS"}

gpsdecode:
{"class":"AIS","device":"stdin","type":17,"repeat":0,"mmsi":804870766,"scaled":true,"lon":134.4,"lat":173.8,"data":"272:7f7f6289c1838dbd78cc7bb8b17163c7dd0631b93feefe7ba7977f972be85d6e506f"}

GPSD issue: https://savannah.nongnu.org/bugs/index.php?44619

**Comment by eric-s-raymond** [comment]
My bug.  The GPSD type 17 decoder was looking for unsigned rather than signed latitude.  Fix is trivial and should be in GPSD head within minutes.  Kurt, you can close this one.

I'd have caught this sooner, but I havce no known-good decodes for type 17 and thus none wi

**Comment by redhog** [comment]
Thanks @eric-s-raymond !

By the way, I caught this while working on https://github.com/SkyTruth/gpsd_format - a validator for the GPSD format that I'm writing to validate the output of libais' aisdecode --gpsd compatibility mode. Maybe that project could be of interest to you too?
