### ISSUE TITLE
Get travis-cl working

### ISSUE THREAD

**Issue by schwehr** [schwehr/libais#87]
Kevin got it started, but I can't figure out the C++11 compiler issue

http://stackoverflow.com/questions/30378880/ive-got-a-cpython-c-module-with-c11-code-but-i-cant-seem-to-build-on-trav

**Comment by geowurster** [comment]
@schwehr Have you looked at the [container testing](http://docs.travis-ci.com/user/workers/container-based-infrastructure/)?  Might give you some more flexibility but you don't have `sudo` and are limited to whatever PPA's are whitelisted.

Travis also has a specific way to [define environment variables](http://docs.travis-ci.com/user/environment-variables/) that might help.

I confess I don't much about c++ so forgive me if neither are useful.

**Comment by schwehr** [comment]
Bummer that c++ tests run for both python 2.7 and python 3.4, but it's working.
